/*
DROP DATABASE IF EXISTS EDUSOHO;
CREATE DATABASE EDUSOHO;
USE EDUSOHO;*/


DROP TABLE IF EXISTS `NAVIGATION`;
CREATE TABLE `NAVIGATION` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '导航ID',
  `NAME` VARCHAR(255) NOT NULL COMMENT '导航名称',
  `URL` VARCHAR(300) NOT NULL COMMENT '链接地址',
  `SEQUENCE` TINYINT(4) UNSIGNED NOT NULL COMMENT '显示顺序',
  `PID` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '父导航ID',
  `CREATETIME` VARCHAR(16) NOT NULL COMMENT '创建时间',
  `ISOPEN` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '默认1，为开启',
  `ISNEWWIN` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '默认为1,另开窗口',
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='导航数据表';

DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER`(
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
	`USERNAME` VARCHAR(128) NOT NULL COMMENT '用户名称',
	`PASSWORD` VARCHAR(255) NOT NULL COMMENT '用户密码',
	`NAME` VARCHAR(255) NOT NULL COMMENT '用户姓名',
	`SEX` CHAR(10) DEFAULT 'SCORI' COMMENT '用户性别',
	`EMAIL` VARCHAR(64) DEFAULT NULL COMMENT '用户邮件地址',
	`AVATAR` VARCHAR(255) DEFAULT '' COMMENT '用户头像',
	`LOCKED` INT(2) DEFAULT 0 COMMENT '是否被冻结',
	`CREATETIME` VARCHAR(32) NOT NULL COMMENT '用户创建时间',
	PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='导航数据表';

INSERT INTO `user` VALUES ('1', 'admin', '14e1b600b1fd579f47433b88e8d85291', '初始化管理员', '', 'admin@email.com', '', '0', NOW());


