/*
DROP DATABASE IF EXISTS EDUSOHO;
CREATE DATABASE EDUSOHO;
USE EDUSOHO;*/


DROP TABLE IF EXISTS `NAVIGATION`;
CREATE TABLE `NAVIGATION` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '导航ID',
  `NAME` VARCHAR(255) NOT NULL COMMENT '导航名称',
  `URL` VARCHAR(300) NOT NULL COMMENT '链接地址',
  `SEQUENCE` TINYINT(4) UNSIGNED NOT NULL COMMENT '显示顺序',
  `PID` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '父导航ID',
  `CREATETIME` VARCHAR(16) NOT NULL COMMENT '创建时间',
  `ISOPEN` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '默认1，为开启',
  `ISNEWWIN` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '默认为1,另开窗口',
  PRIMARY KEY  (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='导航数据表';

DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER`(
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
	`USERNAME` VARCHAR(128) NOT NULL COMMENT '用户名称',
	`PASSWORD` VARCHAR(255) NOT NULL COMMENT '用户密码',
	`NAME` VARCHAR(255) DEFAULT NULL COMMENT '用户姓名',
	`ROLE` VARCHAR(64)  DEFAULT 'STUDENT' COMMENT '用户角色',
	`SEX` CHAR(10) DEFAULT 'SCORI' COMMENT '用户性别',
	`EMAIL` VARCHAR(64) DEFAULT NULL COMMENT '用户邮件地址',
	`AVATAR` VARCHAR(255) DEFAULT '/resource/images/deault_head.png' COMMENT '用户头像',
	`LOCKED` INT(2) DEFAULT 0 COMMENT '是否被冻结',
	`CREATETIME` VARCHAR(32) NOT NULL COMMENT '用户创建时间',
	`PROMOTED`	INT(2) DEFAULT NULL COMMENT '该用户是否被推荐',
	`PROMOTEDTIME`	VARCHAR(32) DEFAULT NULL COMMENT '该用户被推荐的时间',
	PRIMARY KEY  (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户信息表';

INSERT INTO `user` VALUES ('1', 'admin', '14e1b600b1fd579f47433b88e8d85291', '初始化管理员', 'SUPERADMIN','', 'admin@email.com', '/resource/images/deault_head.png', '0', NOW(),NULL,NULL);

DROP TABLE IF EXISTS `CATEGORY`;
CREATE TABLE `CATEGORY`(
	`ID` int(11) unsigned NOT NULL auto_increment COMMENT '分类ID',
	`NAME` varchar(255) NOT NULL COMMENT '分类名称',
	`PID` int(11) unsigned NOT NULL COMMENT '分类的父分类ID',
	`SORT` int(5) DEFAULT 0 COMMENT '分类显示序号',
	`DESCRIPTION` TEXT COMMENT '分类描述',
	PRIMARY KEY  (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='课程分类表';

DROP TABLE IF EXISTS `LOGIN_LOG`;
CREATE TABLE `LOGIN_LOG`
(
	`ID` int(11) unsigned NOT NULL auto_increment COMMENT '日志ID',
	`USERNAME` VARCHAR(128) NOT NULL COMMENT '用户名称',
	`LOGINIP`  VARCHAR(128) NOT NULL COMMENT '用户此次登录IP',
	`LOGINTIME` VARCHAR(32) NOT NULL COMMENT '用户此次登录时间',
	`LOGINRES`  INT(2) NOT NULL COMMENT '用户登录结果',
	 PRIMARY KEY  (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户登录日志表';